#### <center> EXPERIMENT 2
## <center> NUMERICAL PYTHON (NUMPY)

##### Name: Trangia, Klein Isshi G.
##### Section: 2ECE-D
##### Date Submitted: September 5, 2024

### __NORMALIZATION PROBLEM__

In [8]:
import numpy as np

In [10]:
x = np.random.random((5,5))

In [12]:
print (x)

[[0.02422324 0.14676688 0.90847636 0.93666911 0.39985048]
 [0.15663636 0.10993361 0.89214805 0.84252538 0.70655023]
 [0.0693863  0.70711458 0.43923381 0.49077358 0.69919669]
 [0.68087253 0.59792772 0.2756028  0.67996976 0.76115538]
 [0.76490259 0.9345008  0.68591964 0.29857846 0.86051929]]


In [14]:
a = x.mean()

In [16]:
b = x.std()

In [26]:
normal = (x-a)/b

In [28]:
print (normal)

[[-1.84371517 -1.42419269  1.18348466  1.28000126 -0.55777263]
 [-1.39040496 -1.5502897   1.12758546  0.95770453  0.49219984]
 [-1.68910153  0.49413188 -0.4229456  -0.24650157  0.46702534]
 [ 0.40429344  0.12033568 -0.98312884  0.40120285  0.67913807]
 [ 0.69196647  1.27257813  0.42157197 -0.90447273  1.01930584]]


In [30]:
np.save ('X_normalized.npy',normal)

### __DIVISIBLE BY 3 PROBLEM__

In [84]:
k = np.arange(1,101)
i = np.square (k)
g = i.reshape (10,10)

print (g)

[[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]


In [86]:
t = g [g%3==0]

print (t)

[   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]


In [88]:
np.save ('div_by_3.npy',t)